version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: order_tracker
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  flask:
    container_name: flask
    build: ./backend
    entrypoint: ./entrypoint.sh
    depends_on:
      - db
      - redis
    ports:
      - 5001:5000
  react:
    container_name: react
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - flask
  redis:
    image: redis
    ports:
      - 6379:6379

