"""added index

Revision ID: 8c3c66794dca
Revises: b61654f87ca0
Create Date: 2022-06-16 19:06:17.488568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c3c66794dca'
down_revision = 'b61654f87ca0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_sheet')
    op.create_index(op.f('ix_order_order_number'), 'order', ['order_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_order_number'), table_name='order')
    op.create_table('order_sheet',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('order_number', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('delivery_expected', sa.DATE(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
